### PR TITLE
Trace for Vs code problem matcher

### PR DESCRIPTION
**Pull request by Sacramentix**
I've added 2 Sys.println to easely keep track of each build independently, so we can add "Build started" and "Build finished" to Vs code problem matcher.

### CODE REVIEW

**Comment by benmerckx** [comment]
Could you post an example of what the problem matcher looks like? I'd like to see the use case.

**Comment by Sacramentix** [comment]
```json
{
	"tasks": {
		"version": "2.0.0",
		"tasks": [
			{
				"label": "Haxe build",
				"type": "shell",
				"options": {
					"cwd": "${workspaceFolder:back}"
				},
				"command": "haxe node.hxml",
				"problemMatcher": [
					"$haxe"
				]
			},
			{
				"label": "Haxe dev",
				"type": "shell",
				"options": {
					"cwd": "${workspaceFolder:back}"
				},
				"command": "lix watch node.hxml",
				"isBackground": true,
				"problemMatcher": [
					"$haxe",
					{	
						"base": "$haxe",
						"background": {
							"activeOnStart": true,
							"beginsPattern": "name",
							"endsPattern": "Build completed in"
						}
					}
				]
			}
		]
	},
	"launch": {
		"configurations": [	
			{
				"name": "Nodemon backend",
				"console": "integratedTerminal",
				"internalConsoleOptions": "neverOpen",
				"cwd": "${workspaceFolder:bin}",
				"program": "App.js",
				"request": "launch",
				"preLaunchTask": "Haxe dev",
				"restart": true,
				"sourceMaps": true,
				"runtimeExecutable": "nodemon",
				"skipFiles": [
					"<node_internals>/**"
				],
				"type": "pwa-node"
			},
			{
				"name": "Node backend",
				"program": "app.js",
				"cwd": "${workspaceFolder:bin}",
				"request": "launch",
				"preLaunchTask": "Haxe build",
				"sourceMaps": true,
				"skipFiles": [
					"<node_internals>/**"
				],
				"type": "pwa-node"
			}
		]
	}
}
```
I have a Haxe dev task that is a background one because it never end so i need to provide begin and end pattern to let vs code know when the first build finish. Vs code also put error catched between the begin and end in the problem tab.
When the Haxe dev task display > Build completed in Nodemon create dev sever for the js part with a debugger attached.

**Comment by benmerckx** [comment]
I've exposed these under an extra define flag (`-D watch.verbose`)

**Comment by Sacramentix** [comment]
Thank you !

**Pull request merged**
