### PR TITLE
Recurse manually

### PR DESCRIPTION
**Pull request by lbergman**
As mentioned here https://github.com/benmerckx/watch/issues/3#issuecomment-982723883, files are not watched recursively on linux.
This PR simply does manual recursion instead on all targets.

### CODE REVIEW

**Comment by benmerckx** [comment]
Does this react to creating new files during watching?

**Comment by lbergman** [comment]
Will test this evening and let you know

**Comment by lbergman** [comment]
Create, rename and delete all trigger for me

**Comment by benmerckx** [comment]
Thanks I intend to check and merge this when I get the time :)

**Pull request merged**
